../../bin/bam2cov:
	g++ -O2 -o ../../bin/bam2cov bam2cov.cpp -lbamtools -L ../../lib/ -I ../../lib/include/
clean:
	rm ../../bin/bam2cov
debug:
	g++ -g -O2 -o ../../bin/bam2cov bam2cov.cpp -lbamtools -L ../../lib/ -I ../../lib/include/
