export BINDIR = ../../bin
install:
		@cp hupan ${BINDIR};\
		cp hupanLSF ${BINDIR};\
		cp hupanSLURM ${BINDIR};\
		cp adjCdhit.pl ${BINDIR};\
		cp blastCluster.pl ${BINDIR};\
                cp breakGCscaf.pl ${BINDIR};\
		cp filterNovelgene.pl ${BINDIR};\
		cp getTaxClass.pl ${BINDIR};\
		cp getUnalnCtg.pl ${BINDIR};\
		cp linearK.pl ${BINDIR};\
		cp rmCtm.pl ${BINDIR}

clean:
		@rm ${BINDIR}/hupan;\
		rm ${BINDIR}/hupanSLF;\
		rm ${BINDIR}/hupanSLURM;\
		rm ${BINDIR}/adjCdhit.pl;\
		rm ${BINDIR}/blastCluster.pl;\
		rm ${BINDIR}/breakGCscaf.pl;\
		rm ${BINDIR}/filterNovelgene.pl;\
		rm ${BINDIR}/getTaxClass.pl;\
		rm ${BINDIR}/getUnalnCtg.pl;\
		rm ${BINDIR}/linearK.pl;\
		rm ${BINDIR}/rmCtm.pl
