export BINDIR = ../../bin
install:
		@cp plotNovelSeq.R ${BINDIR};\
		cp plotNovelSeq.R ${BINDIR};\
		cp plotQual.R ${BINDIR}

clean:
		@rm ${BINDIR}/pav_plot.R;\
		rm ${BINDIR}/plotNovelSeq.R;\
		rm ${BINDIR}/plotQual.R
